# GLOBAL SITE SETTINGS

# General
seo_title: "Signwriting | Signs and Banner Printing | Signlab Adelaide"
title: "Signlab Adelaide"
company: "Signlab"
description: "Signwriting Signs and Banner Printing"

# Contact Info
email: enquiries@signlab.com.au
phone: 08 8240 0925
fax: (05) 555 555
address: "222 Port Road, Alberton, SA 5014"

# Social Networks
facebook: ""

# Google Map
google_map: ""

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"