# GLOBAL SITE SETTINGS

# General
seo_title: ""
title: ""
company: ""
logo: "/img/content/logo.png"
description: ""

# Contact Info
email: test@example.com
phone: 08 8240 0925
fax: (05) 555 555
address: "222 Port Road, Alberton, SA 5014"

# Social Networks
facebook: ""

# Google Map
google_map: ""

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"